export const tools = [
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce the file size of your PDF',
    path: '/compress-pdf',
    color: 'bg-red-500',
    hoverColor: 'hover:bg-red-600',
    icon: 'FileDown',
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one',
    path: '/merge-pdf',
    color: 'bg-purple-500',
    hoverColor: 'hover:bg-purple-600',
    icon: 'FilePlus2',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Split a PDF into separate pages',
    path: '/split-pdf',
    color: 'bg-indigo-500',
    hoverColor: 'hover:bg-indigo-600',
    icon: 'Scissors',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to JPG images',
    path: '/pdf-to-jpg',
    color: 'bg-amber-500',
    hoverColor: 'hover:bg-amber-600',
    icon: 'Image',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert images to a PDF document',
    path: '/jpg-to-pdf',
    color: 'bg-yellow-500',
    hoverColor: 'hover:bg-yellow-600',
    icon: 'FileImage',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Extract text content from PDF',
    path: '/pdf-to-word',
    color: 'bg-blue-500',
    hoverColor: 'hover:bg-blue-600',
    icon: 'FileText',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert DOCX documents to PDF',
    path: '/word-to-pdf',
    color: 'bg-blue-600',
    hoverColor: 'hover:bg-blue-700',
    icon: 'FileType',
  },
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text and annotations to PDF',
    path: '/edit-pdf',
    color: 'bg-emerald-500',
    hoverColor: 'hover:bg-emerald-600',
    icon: 'Pencil',
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Draw your signature on a PDF',
    path: '/sign-pdf',
    color: 'bg-teal-500',
    hoverColor: 'hover:bg-teal-600',
    icon: 'PenTool',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add password protection to PDF',
    path: '/protect-pdf',
    color: 'bg-orange-500',
    hoverColor: 'hover:bg-orange-600',
    icon: 'Lock',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password from a PDF',
    path: '/unlock-pdf',
    color: 'bg-green-500',
    hoverColor: 'hover:bg-green-600',
    icon: 'Unlock',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages to any angle',
    path: '/rotate-pdf',
    color: 'bg-pink-500',
    hoverColor: 'hover:bg-pink-600',
    icon: 'RotateCw',
  },
];
